# -*- coding: utf-8 -*-
"""TASK$.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClOo64H374gsYzhcpy8NFAhbDnboWq1e
"""

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run task.py & npx localtunnel --port 8501